apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-lantick-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be-lantick
  template:
    metadata:
      labels:
        app: be-lantick
    spec:
      containers:
      - name: be-lantick
        image: mahesaj/be-lan:kb1
        ports:
        - containerPort: 5000
