apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-landtick-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-landtick
  template:
    metadata:
      labels:
        app: db-landtick
    spec:
      containers:
      - name: db-landtick
        image: mahesaj/db-lantickku:v1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "posgres"
