apiVersion: v1
kind: Service
metadata:
  name: be-lantick-service
  labels:
    app: be-lantick
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30011
  selector:
    app: be-lantick
