apiVersion: v1
kind: Service
metadata:
  name: db-landtick-service
  labels:
    app: db-lantick
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30012
  selector:
    app: db-landtick
